### PR TITLE
Selection Background

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
When hovering a class or function name, the ide will show you some info about it and change the background color of the whole block to `@selection-color`. As it is, sky blue is not very suitable. Here is a much more subtle brown. I think it fits the rest of the theme much better.

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
Yes, this is in reference to #16

**Comment by AuthorOfTheSurf** [comment]
Ugh, I need to ship out https://github.com/AuthorOfTheSurf/hyrule-atom/pull/18 for you. Sorry about that. Work is pretty much done.

Will review this coloring change along with my own changes. What you are saying sounds good.

Quick question: what languages do you use Hyrule for?  `2.0.0` is essentially a lot of JavaScript upgrades and I'd like to update some other languages that people use Hyrule for this December.

**Comment by okonomiyaki3000** [comment]
I'm mainly doing web stuff so typically php, javascript, some less/css, some html/xml, a little python.

**Comment by AuthorOfTheSurf** [comment]
Awesome, tyvm :+1:

**Pull request merged**
